version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=8080
    ports:
      - "8080:8080"
    networks:
      - my-network

  backend:
    build: ./backend
    container_name: backend
    environment:
      - NODE_ENV=development
      - PORT=3000
      - KEYCLOAK_URL=http://keycloak:8080
    ports:
      - "3000:3000"
    depends_on:
      - keycloak
    networks:
      - my-network

  frontend:
    build: ./frontend/dny-netflix
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
